services:
  api:
    environment:
      SMARTBITE_MOBILE_EXPIRY_DETECTOR_BACKEND: onnx
      SMARTBITE_MOBILE_EXPIRY_DETECTOR_ONNX_PATH: models/yolo26s_obb_expdate2k_ft_after_brazil/weights/best.onnx
      SMARTBITE_SVTRV2_REC_BACKEND: onnx
      SMARTBITE_SVTRV2_REC_ONNX_PATH: models/svtrv2/smartbite_svtrv2_expdate_rec_onnx/model.onnx
      SMARTBITE_SVTRV2_DEVICE_MODE: cpu
  worker:
    environment:
      SMARTBITE_MOBILE_EXPIRY_DETECTOR_BACKEND: onnx
      SMARTBITE_MOBILE_EXPIRY_DETECTOR_ONNX_PATH: models/yolo26s_obb_expdate2k_ft_after_brazil/weights/best.onnx
      SMARTBITE_SVTRV2_REC_BACKEND: onnx
      SMARTBITE_SVTRV2_REC_ONNX_PATH: models/svtrv2/smartbite_svtrv2_expdate_rec_onnx/model.onnx
      SMARTBITE_SVTRV2_DEVICE_MODE: cpu
